# bool() - Converts a value to True or False.
# print(bool(0))
# print(bool(0.0))
# print(bool(""))
# print(bool([]))
# print(bool(()))
# print(bool({}))
# print(bool(set()))
# print(bool(None))
# ---\
print("----------------")
print(bool(10))
print(bool(-5))
print(bool(0.5))
print(bool("0"))
print(bool("False"))
print(bool(" "))
print(bool("abc"))
print(bool([1]))
# Important: Any non-empty string becomes True.